name: Plus63
favicon: null
layout_spectrum: 0.2552201591897756
typography_spectrum: 0.7905154395848513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.09849007008597255
  lightness: 0.7495689161587507
  saturation: 0.6915629249997437
  rhythmicContrast: 0.06363940075971186
purpose: []
