name: Plus63
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd9025'
    - '#fdab55'
    - '#fdc084'
    - '#fde7cc'
  brandStrength: 0.5625
  lightness: 0.7495689161587507
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
